project_name: "hosting-template"
region: "ap-south-1"

network:
  vpc_cidr: "10.0.0.0/16"
  availability_zones: ["ap-south-1a", "ap-south-1b"]
  public_subnets: ["10.0.1.0/24", "10.0.2.0/24"]
  private_subnets: ["10.0.11.0/24", "10.0.12.0/24"]
  nat_gateway: true

compute:
  instance_type: "t3.micro"
  app_port: 3000
  scaling:
    min: 2
    max: 5
    desired: 2

database:
  enable: true
  engine: "postgres" # postgres | mysql | external | none
  version: "14" # PG: 11,12,13,14 | MySQL: 5.7, 8.0
  instance_class: "db.t3.micro"
  storage_gb: 20
  multi_az: false
  publicly_accessible: false

cache:
  enabled: true
  node_type: "cache.t3.micro"
  num_nodes: 1

frontend:
  enabled: true

ci_cd:
  owner: "EswarTai" # username
  repo: "Cloud_Hosting_Template" # repo name
