name: Backend CI/CD

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  id-token: write

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS OIDC Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ci-session

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          ECR="${{ secrets.ECR_REPO }}"
          docker build -t "$ECR:latest" app/backend_p/
          docker tag "$ECR:latest" "$ECR:${{ github.sha }}"

      - name: Push Image
        run: |
          ECR="${{ secrets.ECR_REPO }}"
          docker push "$ECR:latest"
          docker push "$ECR:${{ github.sha }}"

      - name: Update SSM Parameter (image uri)
        run: |
          aws ssm put-parameter \
            --name "/hosting-template/compute/backend/image_uri" \
            --value "${{ secrets.ECR_REPO }}:${{ github.sha }}" \
            --type String \
            --overwrite

      - name: Refresh ASG Safely
        run: |
          ASG_NAME="hosting-template-asg"

          echo "ðŸ” Checking if an Instance Refresh is already running..."

          CURRENT_STATUS=$(aws autoscaling describe-instance-refreshes \
            --auto-scaling-group-name "$ASG_NAME" \
            --max-records 1 \
            --query "InstanceRefreshes[0].Status" \
            --output text 2>/dev/null || echo "NONE")

          echo "Current Refresh Status: $CURRENT_STATUS"

          if [ "$CURRENT_STATUS" = "InProgress" ]; then
            echo "A refresh is already in progress. Skipping new refresh."
            exit 0
          fi

          echo "ðŸš€Starting new instance refresh..."
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name "$ASG_NAME" \
            --strategy Rolling

          echo "Instance refresh triggered successfully."
