name: Frontend Deployment

on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: frontend-session

      #################################################################
      # 1. Fetch S3 bucket + CloudFront ID stored by Terraform in SSM #
      #################################################################
      - name: Fetch frontend bucket from SSM
        id: bucket
        run: |
          BUCKET=$(aws ssm get-parameter \
            --name "/hosting-template/frontend/bucket" \
            --query "Parameter.Value" \
            --output text)

          echo "bucket=$BUCKET" >> $GITHUB_OUTPUT

      - name: Fetch CloudFront ID from SSM
        id: cf
        run: |
          CFID=$(aws ssm get-parameter \
            --name "/hosting-template/frontend/cdn_id" \
            --query "Parameter.Value" \
            --output text)

          echo "cloudfront_id=$CFID" >> $GITHUB_OUTPUT

      ###########################################
      # 2. Install Dependencies & Build Frontend #
      ###########################################
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: app/frontend
        run: npm install --legacy-peer-deps

      - name: Build
        working-directory: app/frontend
        run: npm run build

      ###########################################
      # 3. Deploy to S3                         #
      ###########################################
      - name: Upload to S3
        run: |
          aws s3 sync app/frontend/dist \
            s3://${{ steps.bucket.outputs.bucket }} \
            --delete

      ###########################################
      # 4. Invalidate CloudFront Cache          #
      ###########################################
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ steps.cf.outputs.cloudfront_id }} \
            --paths "/*"

      - name: Done
        run: echo "ðŸŽ‰ Frontend deployed successfully!"
