"backend":
  "backend":
    "asg_name": "hosting-template-asg"
    "image_repo": "467410558790.dkr.ecr.ap-south-1.amazonaws.com/hosting-template-backend-backend"
    "launch_template_id": "lt-0e2f0a894b024c181"
    "port": 3000
    "region": "ap-south-1"
    "ssm_param_name": "/hosting-template/compute/backend/image_tag"
"frontend":
  "frontend-app":
    "bucket": "hosting-template-frontend-2fb7a51e"
    "cloudfront_id": "E2DD4GK72PWSH4"
    "region": "ap-south-1"
