"backend":
  "backend":
    "asg_name": "hosting-template-asg"
    "image_repo": "467410558790.dkr.ecr.ap-south-1.amazonaws.com/hosting-template-backend-backend"
    "launch_template_id": "lt-0898f2d0d23ef73b3"
    "port": 3000
    "region": "ap-south-1"
    "ssm_param_name": "/hosting-template/compute/backend/image_tag"
"frontend":
  "frontend-app":
    "bucket": "hosting-template-frontend-558da195"
    "cloudfront_id": "E35CLHKO767ZBH"
    "region": "ap-south-1"
