"backend":
  "backend":
    "asg_name": "hosting-template-asg"
    "image_repo": "467410558790.dkr.ecr.ap-south-1.amazonaws.com/hosting-template-backend-backend"
    "launch_template_id": "lt-061802a54998f4f1b"
    "port": 3000
    "region": "ap-south-1"
    "ssm_param_name": "/hosting-template/compute/backend/image_tag"
"frontend":
  "frontend-app":
    "bucket": "hosting-template-frontend-e57c199f"
    "cloudfront_id": "E10RU677FJTKE"
    "region": "ap-south-1"
